[package]
name = "redis_queue_dispatcher"
version = "0.1.0"
authors = ["Carter McKinnon <cartermckinnon@gmail.com>"]
edition = "2018"

[dependencies]
redis = "0.15.1"
argparse = "0.2.2"
ctrlc = { version = "3.1.3", features = ["termination"] }